name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.9.13
homepage: https://github.com/brianegan/chewie

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  open_iconic_flutter: ^0.3.0
  video_player: ^0.11.1+2
  wakelock: ^0.2.0+1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
